### PR TITLE
Remove unused test file

### PR DESCRIPTION
**Pull request by lukehoban**

### CODE REVIEW

**Comment by lukehoban** [comment]
Do we even use `gomod-override` at all anymore?  I see only one use of it outside this repo at https://github.com/search?q=org%3Apulumi%20gomod-override&type=code - and I believe that is an abandoned project.

If we can just delete the whole thing, that will also allow closing out https://github.com/search?q=org%3Apulumi%20gomod-override&type=code.

**Review by iwahbe — APPROVED** [review]
Should be fine. I'm not aware of any use of `gomod-override`. Lets delete the whole thing.

**Comment by iwahbe** [comment]
I opened https://github.com/pulumi/scripts/pull/140 to remove the whole folder.

**Comment by lukehoban** [comment]
Closing out as #140 will subsume this.

**Pull request closed without merging**
