### PR TITLE
Explicitly install Node 12.18.2

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Comment by cnunciato** [comment]
Does [this line](https://github.com/pulumi/scripts/blob/b369d1df6a1f6c2db8d83d1f10a9b48c7c25a0eb/ci/install-common-toolchain.sh#L1) conflict with what's in this PR? Should the change be made there instead?

More broadly, I'm not sure how this script is used elsewhere, but we don't take an explicit dependency on nvm in the docs repo; we install Node 12 with a GitHub Action. (I only mentioned `nvm` in that error message because it's commonly used in local development, and enough folks run into issues running older Node versions that it helped to make this more explicit and easily remedied.) I'm not sure I'd recommend taking a dependency on nvm at this level, though. (But again, I'm not sure where/how this script is used.)

**Comment by lblackstone** [comment]
> Does [this line](https://github.com/pulumi/scripts/blob/b369d1df6a1f6c2db8d83d1f10a9b48c7c25a0eb/ci/install-common-toolchain.sh#L1) conflict with what's in this PR? Should the change be made there instead?

Oops, totally missed that. Yes, I'll change it there instead.

This script is used by all of the provider repos to install deps for CI. It shouldn't affect users.

**Comment by pgavlin** [comment]
> As long as Node 12.x is what's on the path, though, the docs build should be happy. Doesn't have be done with nvm.

FWIW, I do think that we should loosen the version check. I have v14 installed and things work fine ¯\_(ツ)_/¯

**Comment by pgavlin** [comment]
(after I comment out the check, of course)

**Comment by lblackstone** [comment]
@lukehoban Does this change impact our test coverage? I'm unclear if the previous pinned version is important now.

**Comment by lukehoban** [comment]
In `pulumi/pulumi` we override this with three different values - so I don’t think the default ever matters there?

https://github.com/pulumi/pulumi/blob/master/.travis.yml#L3

Honestly not sure the impact this has in other repos, but I worry a bit less other places. I do think in general all other repos should test against the LTS which we document as recommended.

**Comment by pgavlin** [comment]
This may have broken https://github.com/pulumi/pulumi: https://travis-ci.com/github/pulumi/pulumi/builds/174694836

**Comment by pgavlin** [comment]
(it might be a coincidence--still looking into it)

**Comment by metral** [comment]
This has also broken p/eks: https://travis-ci.com/github/pulumi/pulumi-eks/builds/174679443#L918

**Pull request merged**
